-- WARNING: This was a big refactor and this migration is manually adjusted. DON'T use the `dotnet ef database update` for this one.

START TRANSACTION;

CREATE TABLE nadcl.dota_fantasy_leagues (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    league_id integer NOT NULL,
    league_name text,
    is_active boolean NOT NULL,
    fantasy_draft_locked_date bigint NOT NULL,
    league_start_time bigint NOT NULL,
    league_end_time bigint NOT NULL,
    CONSTRAINT "PK_dota_fantasy_leagues" PRIMARY KEY (id),
    CONSTRAINT "FK_dota_fantasy_leagues_dota_leagues_league_id" FOREIGN KEY (league_id) REFERENCES nadcl.dota_leagues (id) ON DELETE CASCADE
);

ALTER TABLE nadcl.dota_leagues DROP COLUMN fantasy_draft_locked_date;

ALTER TABLE nadcl.dota_leagues DROP COLUMN league_end_time;

ALTER TABLE nadcl.dota_leagues DROP COLUMN league_id;

ALTER TABLE nadcl.dota_leagues DROP COLUMN league_start_time;

ALTER TABLE nadcl.dota_fantasy_players DROP COLUMN league_id;

ALTER TABLE nadcl.dota_fantasy_drafts RENAME COLUMN league_id TO fantasy_league_id;

ALTER TABLE nadcl.dota_fantasy_players ADD fantasy_league_id integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_dota_match_history_league_id" ON nadcl.dota_match_history (league_id);

CREATE INDEX "IX_dota_match_details_league_id" ON nadcl.dota_match_details (league_id);

CREATE UNIQUE INDEX "IX_dota_gc_match_metadata_match_id" ON nadcl.dota_gc_match_metadata (match_id);

CREATE INDEX "IX_dota_fantasy_players_fantasy_league_id" ON nadcl.dota_fantasy_players (fantasy_league_id);

CREATE INDEX "IX_dota_fantasy_drafts_fantasy_league_id" ON nadcl.dota_fantasy_drafts (fantasy_league_id);

CREATE INDEX "IX_dota_fantasy_leagues_league_id" ON nadcl.dota_fantasy_leagues (league_id);

ALTER TABLE nadcl.dota_fantasy_drafts ADD CONSTRAINT "FK_dota_fantasy_drafts_dota_fantasy_leagues_fantasy_league_id" FOREIGN KEY (fantasy_league_id) REFERENCES nadcl.dota_fantasy_leagues (id) ON DELETE CASCADE;

ALTER TABLE nadcl.dota_fantasy_players ADD CONSTRAINT "FK_dota_fantasy_players_dota_fantasy_leagues_fantasy_league_id" FOREIGN KEY (fantasy_league_id) REFERENCES nadcl.dota_fantasy_leagues (id) ON DELETE CASCADE;

ALTER TABLE nadcl.dota_gc_match_metadata ADD CONSTRAINT "FK_dota_gc_match_metadata_dota_match_details_match_id" FOREIGN KEY (match_id) REFERENCES nadcl.dota_match_details (match_id) ON DELETE CASCADE;

ALTER TABLE nadcl.dota_match_details ADD CONSTRAINT "FK_dota_match_details_dota_leagues_league_id" FOREIGN KEY (league_id) REFERENCES nadcl.dota_leagues (id) ON DELETE CASCADE;

ALTER TABLE nadcl.dota_match_history ADD CONSTRAINT "FK_dota_match_history_dota_leagues_league_id" FOREIGN KEY (league_id) REFERENCES nadcl.dota_leagues (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240216062618_FantasyLeagueRefactor', '8.0.1');

COMMIT;


