drop view if exists nadcl.fantasy_normalized_averages;
create view nadcl.fantasy_normalized_averages as
with avg_scores as (
	select 
		fantasy_player_id,
		count(DISTINCT match_details_player_id) as matches_played,
		avg(kills_points) as kills_points,
		avg(deaths_points) as deaths_points,
		avg(assists_points) as assists_points,
		avg(last_hits_points) as last_hits_points,
		avg(gold_per_min_points) as gold_per_min_points,
		avg(xp_per_min_points) as xp_per_min_points,
		avg(networth_points) as networth_points,
		avg(hero_damage_points) as hero_damage_points,
		avg(tower_damage_points) as tower_damage_points,
		avg(hero_healing_points) as hero_healing_points,
		avg(gold_points) as gold_points,
		avg(hero_xp_points) as hero_xp_points,
		avg(camps_stacked_points) as camps_stacked_points,
		avg(rampages_points) as rampages_points,
		avg(triple_kills_points) as triple_kills_points,
		avg(aegis_snatched_points) as aegis_snatched_points,
		avg(rapiers_purchased_points) as rapiers_purchased_points,
		avg(couriers_killed_points) as couriers_killed_points,
		avg(support_gold_spent_points) as support_gold_spent_points,
		avg(observer_wards_placed_points) as observer_wards_placed_points,
		avg(sentry_wards_placed_points) as sentry_wards_placed_points,
		avg(wards_dewarded_points) as wards_dewarded_points,
		avg(stun_duration_points) as stun_duration_points,
		avg(total_match_fantasy_points) as total_match_fantasy_points,
		avg(fight_score) as fight_score,
		avg(farm_score) as farm_score,
		avg(support_score) as support_score,
		avg(push_score) as push_score
	from nadcl.fantasy_player_points fpp
	where fight_score is not null
	group by fantasy_player_id
), min_max as (
	select
		min(matches_played) as matches_played_min,
		max(matches_played) as matches_played_max,
		min(kills_points) as kills_points_min,
		max(kills_points) as kills_points_max,
		min(deaths_points) as deaths_points_min,
		max(deaths_points) as deaths_points_max,
		min(assists_points) as assists_points_min,
		max(assists_points) as assists_points_max,
		min(last_hits_points) as last_hits_points_min,
		max(last_hits_points) as last_hits_points_max,
		min(gold_per_min_points) as gold_per_min_points_min,
		max(gold_per_min_points) as gold_per_min_points_max,
		min(xp_per_min_points) as xp_per_min_points_min,
		max(xp_per_min_points) as xp_per_min_points_max,
		min(networth_points) as networth_points_min,
		max(networth_points) as networth_points_max,
		min(hero_damage_points) as hero_damage_points_min,
		max(hero_damage_points) as hero_damage_points_max,
		min(tower_damage_points) as tower_damage_points_min,
		max(tower_damage_points) as tower_damage_points_max,
		min(hero_healing_points) as hero_healing_points_min,
		max(hero_healing_points) as hero_healing_points_max,
		min(gold_points) as gold_points_min,
		max(gold_points) as gold_points_max,
		min(hero_xp_points) as hero_xp_points_min,
		max(hero_xp_points) as hero_xp_points_max,
		min(camps_stacked_points) as camps_stacked_points_min,
		max(camps_stacked_points) as camps_stacked_points_max,
		min(rampages_points) as rampages_points_min,
		max(rampages_points) as rampages_points_max,
		min(triple_kills_points) as triple_kills_points_min,
		max(triple_kills_points) as triple_kills_points_max,
		min(aegis_snatched_points) as aegis_snatched_points_min,
		max(aegis_snatched_points) as aegis_snatched_points_max,
		min(rapiers_purchased_points) as rapiers_purchased_points_min,
		max(rapiers_purchased_points) as rapiers_purchased_points_max,
		min(couriers_killed_points) as couriers_killed_points_min,
		max(couriers_killed_points) as couriers_killed_points_max,
		min(support_gold_spent_points) as support_gold_spent_points_min,
		max(support_gold_spent_points) as support_gold_spent_points_max,
		min(observer_wards_placed_points) as observer_wards_placed_points_min,
		max(observer_wards_placed_points) as observer_wards_placed_points_max,
		min(sentry_wards_placed_points) as sentry_wards_placed_points_min,
		max(sentry_wards_placed_points) as sentry_wards_placed_points_max,
		min(wards_dewarded_points) as wards_dewarded_points_min,
		max(wards_dewarded_points) as wards_dewarded_points_max,
		min(stun_duration_points) as stun_duration_points_min,
		max(stun_duration_points) as stun_duration_points_max,
		min(total_match_fantasy_points) as total_match_fantasy_points_min,
		max(total_match_fantasy_points) as total_match_fantasy_points_max,
		
		-- Valve scores
		min(fight_score) as fight_score_min,
		max(fight_score) as fight_score_max,
		min(farm_score) as farm_score_min,
		max(farm_score) as farm_score_max,
		min(support_score) as support_score_min,
		max(support_score) as support_score_max,
		min(push_score) as push_score_min,
		max(push_score) as push_score_max
	from avg_scores
)
select
	fantasy_player_id,
	(matches_played - matches_played_min) / nullif(matches_played_max - matches_played_min, 0)::numeric as matches_played,
	(kills_points - kills_points_min) / nullif(kills_points_max - kills_points_min, 0) as kills_points,
	(deaths_points - deaths_points_min) / nullif(deaths_points_max - deaths_points_min, 0) as deaths_points,
	(assists_points - assists_points_min) / nullif(assists_points_max - assists_points_min, 0) as assists_points,
	(last_hits_points - last_hits_points_min) / nullif(last_hits_points_max - last_hits_points_min, 0) as last_hits_points,
	(gold_per_min_points - gold_per_min_points_min) / nullif(gold_per_min_points_max - gold_per_min_points_min, 0) as gold_per_min_points,
	(xp_per_min_points - xp_per_min_points_min) / nullif(xp_per_min_points_max - xp_per_min_points_min, 0) as xp_per_min_points,
	(networth_points - networth_points_min) / nullif(networth_points_max - networth_points_min, 0) as networth_points,
	(hero_damage_points - hero_damage_points_min) / nullif(hero_damage_points_max - hero_damage_points_min, 0) as hero_damage_points,
	(tower_damage_points - tower_damage_points_min) / nullif(tower_damage_points_max - tower_damage_points_min, 0) as tower_damage_points,
	(hero_healing_points - hero_healing_points_min) / nullif(hero_healing_points_max - hero_healing_points_min, 0) as hero_healing_points,
	(gold_points - gold_points_min) / nullif(gold_points_max - gold_points_min, 0) as gold_points,
	(hero_xp_points - hero_xp_points_min) / nullif(hero_xp_points_max - hero_xp_points_min, 0) as hero_xp_points,
	(camps_stacked_points - camps_stacked_points_min) / nullif(camps_stacked_points_max - camps_stacked_points_min, 0) as camps_stacked_points,
	(rampages_points - rampages_points_min) / nullif(rampages_points_max - rampages_points_min, 0) as rampages_points,
	(triple_kills_points - triple_kills_points_min) / nullif(triple_kills_points_max - triple_kills_points_min, 0) as triple_kills_points,
	(aegis_snatched_points - aegis_snatched_points_min) / nullif(aegis_snatched_points_max - aegis_snatched_points_min, 0) as aegis_snatched_points,
	(rapiers_purchased_points - rapiers_purchased_points_min) / nullif(rapiers_purchased_points_max - rapiers_purchased_points_min, 0) as rapiers_purchased_points,
	(couriers_killed_points - couriers_killed_points_min) / nullif(couriers_killed_points_max - couriers_killed_points_min, 0) as couriers_killed_points,
	(support_gold_spent_points - support_gold_spent_points_min) / nullif(support_gold_spent_points_max - support_gold_spent_points_min, 0) as support_gold_spent_points,
	(observer_wards_placed_points - observer_wards_placed_points_min) / nullif(observer_wards_placed_points_max - observer_wards_placed_points_min, 0) as observer_wards_placed_points,
	(sentry_wards_placed_points - sentry_wards_placed_points_min) / nullif(sentry_wards_placed_points_max - sentry_wards_placed_points_min, 0) as sentry_wards_placed_points,
	(wards_dewarded_points - wards_dewarded_points_min) / nullif(wards_dewarded_points_max - wards_dewarded_points_min, 0) as wards_dewarded_points,
	(stun_duration_points - stun_duration_points_min) / nullif(stun_duration_points_max - stun_duration_points_min, 0) as stun_duration_points,
	(total_match_fantasy_points - total_match_fantasy_points_min) / nullif(total_match_fantasy_points_max - total_match_fantasy_points_min, 0) as total_match_fantasy_points,
	-- Valve scores
	(fight_score - fight_score_min) / nullif(fight_score_max - fight_score_min, 0) as fight_score,
	(farm_score - farm_score_min) / nullif(farm_score_max - farm_score_min, 0) as farm_score,
	(support_score - support_score_min) / nullif(support_score_max - support_score_min, 0) as support_score,
	(push_score - push_score_min) / nullif(push_score_max - push_score_min, 0) as push_score
from avg_scores
	cross join min_max
;

