START TRANSACTION;

CREATE TABLE nadcl.dota_gc_match_metadata (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    match_id bigint NOT NULL,
    lobby_id numeric(20,0) NOT NULL,
    report_until_time numeric(20,0) NOT NULL,
    primary_event_id bigint NOT NULL,
    CONSTRAINT "PK_dota_gc_match_metadata" PRIMARY KEY (id)
);

CREATE TABLE nadcl.dota_gc_match_metadata_team (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    dota_team bigint NOT NULL,
    cm_first_pick boolean NOT NULL,
    cm_captain_player_id integer NOT NULL,
    cm_penalty bigint NOT NULL,
    "GraphExperience" real[] NOT NULL,
    "GraphGoldEarned" real[] NOT NULL,
    "GraphNetworth" real[] NOT NULL,
    "GcMatchMetadataId" bigint,
    CONSTRAINT "PK_dota_gc_match_metadata_team" PRIMARY KEY (id),
    CONSTRAINT "FK_dota_gc_match_metadata_team_dota_gc_match_metadata_GcMatchM~" FOREIGN KEY ("GcMatchMetadataId") REFERENCES nadcl.dota_gc_match_metadata (id)
);

CREATE TABLE nadcl.dota_gc_match_metadata_tip (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    source_player_slot bigint NOT NULL,
    target_player_slot bigint NOT NULL,
    tip_amount bigint NOT NULL,
    "GcMatchMetadataId" bigint,
    CONSTRAINT "PK_dota_gc_match_metadata_tip" PRIMARY KEY (id),
    CONSTRAINT "FK_dota_gc_match_metadata_tip_dota_gc_match_metadata_GcMatchMe~" FOREIGN KEY ("GcMatchMetadataId") REFERENCES nadcl.dota_gc_match_metadata (id)
);

CREATE TABLE nadcl.dota_gc_match_metadata_player (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    player_slot bigint NOT NULL,
    avg_kills_x16 bigint NOT NULL,
    avg_deaths_x16 bigint NOT NULL,
    avg_assists_x16 bigint NOT NULL,
    avg_gpm_x16 bigint NOT NULL,
    avg_xpm_x16 bigint NOT NULL,
    best_kills_x16 bigint NOT NULL,
    best_assists_x16 bigint NOT NULL,
    best_gpm_x16 bigint NOT NULL,
    best_xpm_x16 bigint NOT NULL,
    win_streak bigint NOT NULL,
    best_win_streak bigint NOT NULL,
    fight_score real NOT NULL,
    farm_score real NOT NULL,
    support_score real NOT NULL,
    push_score real NOT NULL,
    avg_stats_calibrated boolean NOT NULL,
    hero_xp bigint NOT NULL,
    camps_stacked bigint NOT NULL,
    lane_selection_flags bigint NOT NULL,
    rampages bigint NOT NULL,
    triple_kills bigint NOT NULL,
    aegis_snatched bigint NOT NULL,
    rapiers_purchased bigint NOT NULL,
    couriers_killed bigint NOT NULL,
    net_worth_rank bigint NOT NULL,
    support_gold_spent bigint NOT NULL,
    observer_wards_placed bigint NOT NULL,
    sentry_wards_placed bigint NOT NULL,
    wards_dewarded bigint NOT NULL,
    stun_duration real NOT NULL,
    team_slot bigint NOT NULL,
    featured_hero_sticker_index bigint NOT NULL,
    featured_hero_sticker_quality bigint NOT NULL,
    game_player_id integer NOT NULL,
    "AbilityUpgrades" integer[] NOT NULL,
    "GcMatchMetadataTeamId" bigint,
    CONSTRAINT "PK_dota_gc_match_metadata_player" PRIMARY KEY (id),
    CONSTRAINT "FK_dota_gc_match_metadata_player_dota_gc_match_metadata_team_G~" FOREIGN KEY ("GcMatchMetadataTeamId") REFERENCES nadcl.dota_gc_match_metadata_team (id)
);

CREATE TABLE nadcl.dota_gc_match_metadata_itempurchase (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    item_id bigint NOT NULL,
    purchase_time bigint NOT NULL,
    "GcMatchMetadataPlayerId" bigint,
    CONSTRAINT "PK_dota_gc_match_metadata_itempurchase" PRIMARY KEY (id),
    CONSTRAINT "FK_dota_gc_match_metadata_itempurchase_dota_gc_match_metadata_~" FOREIGN KEY ("GcMatchMetadataPlayerId") REFERENCES nadcl.dota_gc_match_metadata_player (id)
);

CREATE TABLE nadcl.dota_gc_match_metadata_playerkill (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    victim_slot bigint NOT NULL,
    count bigint NOT NULL,
    "GcMatchMetadataPlayerId" bigint,
    CONSTRAINT "PK_dota_gc_match_metadata_playerkill" PRIMARY KEY (id),
    CONSTRAINT "FK_dota_gc_match_metadata_playerkill_dota_gc_match_metadata_pl~" FOREIGN KEY ("GcMatchMetadataPlayerId") REFERENCES nadcl.dota_gc_match_metadata_player (id)
);

CREATE INDEX "IX_dota_gc_match_metadata_itempurchase_GcMatchMetadataPlayerId" ON nadcl.dota_gc_match_metadata_itempurchase ("GcMatchMetadataPlayerId");

CREATE INDEX "IX_dota_gc_match_metadata_player_GcMatchMetadataTeamId" ON nadcl.dota_gc_match_metadata_player ("GcMatchMetadataTeamId");

CREATE INDEX "IX_dota_gc_match_metadata_playerkill_GcMatchMetadataPlayerId" ON nadcl.dota_gc_match_metadata_playerkill ("GcMatchMetadataPlayerId");

CREATE INDEX "IX_dota_gc_match_metadata_team_GcMatchMetadataId" ON nadcl.dota_gc_match_metadata_team ("GcMatchMetadataId");

CREATE INDEX "IX_dota_gc_match_metadata_tip_GcMatchMetadataId" ON nadcl.dota_gc_match_metadata_tip ("GcMatchMetadataId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240211111101_GcMatchMetadata', '8.0.1');

COMMIT;


