START TRANSACTION;

ALTER TABLE nadcl.dota_gc_match_metadata DROP CONSTRAINT "FK_dota_gc_match_metadata_dota_match_details_match_id";

DROP TABLE nadcl.balance_ledger;

DROP TABLE nadcl.bets_streaks;

DROP TABLE nadcl.bromance_last_60;

DROP TABLE nadcl.match_status;

DROP TABLE nadcl.matches_streaks;

DROP TABLE nadcl.player_match_details;

DROP INDEX nadcl."IX_dota_gc_match_metadata_match_id";

ALTER TABLE nadcl.gc_dota_matches DROP CONSTRAINT "PK_gc_dota_matches";

ALTER TABLE nadcl.gc_dota_matches RENAME TO dota_gc_match_details;

ALTER TABLE nadcl.dota_gc_match_metadata ADD "LeagueId" integer;

ALTER TABLE nadcl.dota_gc_match_details ADD CONSTRAINT "PK_dota_gc_match_details" PRIMARY KEY (match_id);

CREATE TABLE nadcl.discord_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL,
    CONSTRAINT "PK_discord_users" PRIMARY KEY (id)
);

INSERT INTO nadcl.discord_users (id, username)
SELECT discord_id, discord_name
FROM nadcl.discord_ids;

DROP TABLE nadcl.discord_ids;

CREATE TABLE nadcl.dota_gc_match_detail_players (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    account_id bigint NOT NULL,
    player_slot bigint NOT NULL,
    hero_id bigint NOT NULL,
    item_0 integer NOT NULL,
    item_1 integer NOT NULL,
    item_2 integer NOT NULL,
    item_3 integer NOT NULL,
    item_4 integer NOT NULL,
    item_5 integer NOT NULL,
    item_6 integer NOT NULL,
    item_7 integer NOT NULL,
    item_8 integer NOT NULL,
    item_9 integer NOT NULL,
    expected_team_contribution real NOT NULL,
    scaled_metric real NOT NULL,
    previous_rank bigint NOT NULL,
    rank_change integer NOT NULL,
    mmr_type bigint NOT NULL,
    kills bigint NOT NULL,
    deaths bigint NOT NULL,
    assists bigint NOT NULL,
    leaver_status bigint NOT NULL,
    gold bigint NOT NULL,
    last_hits bigint NOT NULL,
    denies bigint NOT NULL,
    gold_per_min bigint NOT NULL,
    xp_per_min bigint NOT NULL,
    gold_spent bigint NOT NULL,
    hero_damage bigint NOT NULL,
    tower_damage bigint NOT NULL,
    hero_healing bigint NOT NULL,
    level bigint NOT NULL,
    time_last_seen bigint NOT NULL,
    player_name text,
    support_ability_value bigint NOT NULL,
    feeding_detected boolean NOT NULL,
    search_rank bigint NOT NULL,
    search_rank_uncertainty bigint NOT NULL,
    rank_uncertainty_change integer NOT NULL,
    hero_play_count bigint NOT NULL,
    party_id numeric(20,0) NOT NULL,
    scaled_hero_damage bigint NOT NULL,
    scaled_tower_damage bigint NOT NULL,
    scaled_hero_healing bigint NOT NULL,
    scaled_kills real NOT NULL,
    scaled_deaths real NOT NULL,
    scaled_assists real NOT NULL,
    claimed_farm_gold bigint NOT NULL,
    support_gold bigint NOT NULL,
    claimed_denies bigint NOT NULL,
    claimed_misses bigint NOT NULL,
    misses bigint NOT NULL,
    pro_name text,
    real_name text,
    active_plus_subscription boolean NOT NULL,
    net_worth bigint NOT NULL,
    bot_difficulty bigint NOT NULL,
    hero_pick_order bigint NOT NULL,
    hero_was_randomed boolean NOT NULL,
    hero_was_dota_plus_suggestion boolean NOT NULL,
    seconds_dead bigint NOT NULL,
    gold_lost_to_death bigint NOT NULL,
    lane_selection_flags bigint NOT NULL,
    bounty_runes bigint NOT NULL,
    outposts_captured bigint NOT NULL,
    team_number integer NOT NULL,
    team_slot bigint NOT NULL,
    "MatchId" numeric(20,0) NOT NULL,
    CONSTRAINT "PK_dota_gc_match_detail_players" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_dota_gc_match_detail_players_dota_gc_match_details_MatchId" FOREIGN KEY ("MatchId") REFERENCES nadcl.dota_gc_match_details (match_id) ON DELETE CASCADE
);

CREATE TABLE nadcl.fantasy_match (
    match_id bigint GENERATED BY DEFAULT AS IDENTITY,
    league_id integer NOT NULL,
    start_time bigint NOT NULL,
    match_history_parsed boolean NOT NULL,
    match_detail_parsed boolean NOT NULL,
    gc_metadata_parsed boolean NOT NULL,
    lobby_type integer NOT NULL,
    "RadiantTeamId" bigint,
    "DireTeamId" bigint,
    radiant_win boolean,
    duration integer,
    pre_game_duration integer,
    first_blood_time integer,
    game_mode integer,
    radiant_score integer,
    dire_score integer,
    CONSTRAINT "PK_fantasy_match" PRIMARY KEY (match_id),
    CONSTRAINT "FK_fantasy_match_dota_teams_DireTeamId" FOREIGN KEY ("DireTeamId") REFERENCES nadcl.dota_teams (id),
    CONSTRAINT "FK_fantasy_match_dota_teams_RadiantTeamId" FOREIGN KEY ("RadiantTeamId") REFERENCES nadcl.dota_teams (id)
);

CREATE TABLE nadcl.dota_gc_match_detail_player_damage_dealt (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    pre_reduction bigint NOT NULL,
    post_reduction bigint NOT NULL,
    damage_type integer NOT NULL,
    "MatchPlayerId" integer NOT NULL,
    CONSTRAINT "PK_dota_gc_match_detail_player_damage_dealt" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_dota_gc_match_detail_player_damage_dealt_dota_gc_match_deta~" FOREIGN KEY ("MatchPlayerId") REFERENCES nadcl.dota_gc_match_detail_players ("Id") ON DELETE CASCADE
);

CREATE TABLE nadcl.dota_gc_match_detail_player_damage_received (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    pre_reduction bigint NOT NULL,
    post_reduction bigint NOT NULL,
    damage_type integer NOT NULL,
    "MatchPlayerId" integer NOT NULL,
    CONSTRAINT "PK_dota_gc_match_detail_player_damage_received" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_dota_gc_match_detail_player_damage_received_dota_gc_match_d~" FOREIGN KEY ("MatchPlayerId") REFERENCES nadcl.dota_gc_match_detail_players ("Id") ON DELETE CASCADE
);

CREATE TABLE nadcl.fantasy_match_player (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    match_id bigint NOT NULL,
    "AccountId" bigint,
    "TeamId" bigint,
    match_detail_player_parsed boolean NOT NULL,
    gc_metadata_player_parsed boolean NOT NULL,
    dota_team_side boolean NOT NULL,
    player_slot integer NOT NULL,
    "HeroId" bigint,
    kills integer,
    deaths integer,
    assists integer,
    last_hits integer,
    denies integer,
    gold_per_min integer,
    xp_per_min integer,
    support_gold_spent integer,
    observer_wards_placed integer,
    sentry_wards_placed integer,
    dewards integer,
    camps_stacked integer,
    stun_duration real,
    level integer,
    net_worth bigint,
    hero_damage integer,
    tower_damage integer,
    hero_healing integer,
    gold integer,
    fight_score real,
    farm_score real,
    support_score real,
    push_score real,
    hero_xp bigint,
    rampages bigint,
    triple_kills bigint,
    aegis_snatched bigint,
    rapiers_purchased bigint,
    couriers_killed bigint,
    CONSTRAINT "PK_fantasy_match_player" PRIMARY KEY (id),
    CONSTRAINT "FK_fantasy_match_player_dota_accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES nadcl.dota_accounts (id),
    CONSTRAINT "FK_fantasy_match_player_dota_heroes_HeroId" FOREIGN KEY ("HeroId") REFERENCES nadcl.dota_heroes (id),
    CONSTRAINT "FK_fantasy_match_player_dota_teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES nadcl.dota_teams (id),
    CONSTRAINT "FK_fantasy_match_player_fantasy_match_match_id" FOREIGN KEY (match_id) REFERENCES nadcl.fantasy_match (match_id) ON DELETE CASCADE
);

CREATE INDEX "IX_dota_gc_match_metadata_LeagueId" ON nadcl.dota_gc_match_metadata ("LeagueId");

CREATE INDEX "IX_dota_gc_match_detail_player_damage_dealt_MatchPlayerId" ON nadcl.dota_gc_match_detail_player_damage_dealt ("MatchPlayerId");

CREATE INDEX "IX_dota_gc_match_detail_player_damage_received_MatchPlayerId" ON nadcl.dota_gc_match_detail_player_damage_received ("MatchPlayerId");

CREATE INDEX "IX_dota_gc_match_detail_players_MatchId" ON nadcl.dota_gc_match_detail_players ("MatchId");

CREATE INDEX "IX_fantasy_match_DireTeamId" ON nadcl.fantasy_match ("DireTeamId");

CREATE INDEX "IX_fantasy_match_RadiantTeamId" ON nadcl.fantasy_match ("RadiantTeamId");

CREATE INDEX "IX_fantasy_match_player_AccountId" ON nadcl.fantasy_match_player ("AccountId");

CREATE INDEX "IX_fantasy_match_player_HeroId" ON nadcl.fantasy_match_player ("HeroId");

CREATE INDEX "IX_fantasy_match_player_match_id" ON nadcl.fantasy_match_player (match_id);

CREATE INDEX "IX_fantasy_match_player_TeamId" ON nadcl.fantasy_match_player ("TeamId");

ALTER TABLE nadcl.dota_gc_match_metadata ADD CONSTRAINT "FK_dota_gc_match_metadata_dota_leagues_LeagueId" FOREIGN KEY ("LeagueId") REFERENCES nadcl.dota_leagues (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240611061359_FantasyMatch', '8.0.1');

COMMIT;


