START TRANSACTION;

CREATE TABLE nadcl.dota_fantasy_normalized_averages (
    fantasy_normalized_averages_table_id bigint GENERATED BY DEFAULT AS IDENTITY,
    fantasy_player_id bigint NOT NULL,
    matches_played numeric,
    kills_points numeric,
    deaths_points numeric,
    assists_points numeric,
    last_hits_points numeric,
    gold_per_min_points numeric,
    xp_per_min_points numeric,
    networth_points numeric,
    hero_damage_points numeric,
    tower_damage_points numeric,
    hero_healing_points numeric,
    gold_points numeric,
    fight_score real,
    farm_score real,
    support_score real,
    push_score real,
    hero_xp_points numeric,
    camps_stacked_points numeric,
    rampages_points numeric,
    triple_kills_points numeric,
    aegis_snatched_points numeric,
    rapiers_purchased_points numeric,
    couriers_killed_points numeric,
    support_gold_spent_points numeric,
    observer_wards_placed_points numeric,
    sentry_wards_placed_points numeric,
    wards_dewarded_points numeric,
    stun_duration_points real,
    total_match_fantasy_points numeric,
    CONSTRAINT "PK_dota_fantasy_normalized_averages" PRIMARY KEY (fantasy_normalized_averages_table_id),
    CONSTRAINT "FK_dota_fantasy_normalized_averages_dota_fantasy_players_fanta~" FOREIGN KEY (fantasy_player_id) REFERENCES nadcl.dota_fantasy_players (id) ON DELETE CASCADE
);

CREATE INDEX "IX_dota_fantasy_normalized_averages_fantasy_player_id" ON nadcl.dota_fantasy_normalized_averages (fantasy_player_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240523061620_FantasyNormalizedTable', '8.0.1');

COMMIT;


