import type { DotaAccount, DotaTeam } from '@/types/Dota';

export interface FantasyMatchPlayer {
    fantasyMatchId: number,
    accountId: number,
    accountFormatted: string,
    teamFormatted: string,
    matchDetailPlayerParsed: boolean,
    gcMetadataPlayerParsed: boolean,
    dotaTeamSide: boolean,
    dotaTeamSideFormatted: string,
    playerSlot: number,
    playerSlotFormatted: string,
    hero: number,
    heroFormatted: string,
    kills: number,
    deaths: number,
    assists: number,
    lastHits: number,
    denies: number,
    goldPerMin: number,
    xpPerMin: number,
    supportGoldSpent: number,
    observerWardsPlaced: number,
    sentyWardsPlaced: number,
    dewards: number,
    campsStacked: number,
    stunDuration: number,
    level: number,
    networth: number,
    heroDamage: number,
    towerDamage: number,
    heroHealing: number,
    gold: number,
    fightScore: number,
    farmScore: number,
    supportScore: number,
    pushScore: number,
    heroXp: number,
    rampages: number,
    tripleKills: number,
    aegisSnatched: number,
    rapiersPurchased: number,
    couriersKilled: number
}