START TRANSACTION;

CREATE TABLE nadcl.dota_fantasy_league_weights (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    fantasy_league_id integer NOT NULL,
    kills_weight numeric NOT NULL,
    deaths_weight numeric NOT NULL,
    assists_weight numeric NOT NULL,
    last_hits_weight numeric NOT NULL,
    gold_per_min_weight numeric NOT NULL,
    xp_per_min_weight numeric NOT NULL,
    networth_weight numeric NOT NULL,
    hero_damage_weight numeric NOT NULL,
    tower_damage_weight numeric NOT NULL,
    hero_healing_weight numeric NOT NULL,
    gold_weight numeric NOT NULL,
    scaled_hero_damage_weight numeric NOT NULL,
    scaled_tower_damage_weight numeric NOT NULL,
    scaled_hero_healing_weight numeric NOT NULL,
    fight_score_weight numeric NOT NULL,
    farm_score_weight numeric NOT NULL,
    support_score_weight numeric NOT NULL,
    push_score_weight numeric NOT NULL,
    hero_xp_weight numeric NOT NULL,
    camps_stacked_weight numeric NOT NULL,
    rampages_weight numeric NOT NULL,
    triple_kills_weight numeric NOT NULL,
    aegis_snatched_weight numeric NOT NULL,
    rapiers_purchased_weight numeric NOT NULL,
    couriers_killed_weight numeric NOT NULL,
    networth_rank_weight numeric NOT NULL,
    support_gold_spent_weight numeric NOT NULL,
    observer_wards_placed_weight numeric NOT NULL,
    sentry_wards_placed_weight numeric NOT NULL,
    wards_dewarded_weight numeric NOT NULL,
    stun_duration_weight numeric NOT NULL,
    CONSTRAINT "PK_dota_fantasy_league_weights" PRIMARY KEY (id),
    CONSTRAINT "FK_dota_fantasy_league_weights_dota_fantasy_leagues_fantasy_le~" FOREIGN KEY (fantasy_league_id) REFERENCES nadcl.dota_fantasy_leagues (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_dota_fantasy_league_weights_fantasy_league_id" ON nadcl.dota_fantasy_league_weights (fantasy_league_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240225050151_FantasyLeagueWeights', '8.0.1');

COMMIT;


